// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module nn_inference_hwmm_layer2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_address0,
        input_0_ce0,
        input_0_q0,
        input_0_address1,
        input_0_ce1,
        input_0_q1,
        output_0_address0,
        output_0_ce0,
        output_0_we0,
        output_0_d0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_pp0_stage0 = 10'd4;
parameter    ap_ST_fsm_state6 = 10'd8;
parameter    ap_ST_fsm_pp1_stage0 = 10'd16;
parameter    ap_ST_fsm_state10 = 10'd32;
parameter    ap_ST_fsm_pp2_stage0 = 10'd64;
parameter    ap_ST_fsm_state14 = 10'd128;
parameter    ap_ST_fsm_pp3_stage0 = 10'd256;
parameter    ap_ST_fsm_state18 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] input_0_address0;
output   input_0_ce0;
input  [31:0] input_0_q0;
output  [5:0] input_0_address1;
output   input_0_ce1;
input  [31:0] input_0_q1;
output  [4:0] output_0_address0;
output   output_0_ce0;
output   output_0_we0;
output  [31:0] output_0_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] input_0_address0;
reg input_0_ce0;
reg[5:0] input_0_address1;
reg input_0_ce1;
reg[4:0] output_0_address0;
reg output_0_ce0;
reg output_0_we0;
reg[31:0] output_0_d0;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [10:0] weights_layer2_weights_V_address0;
reg    weights_layer2_weights_V_ce0;
wire  signed [10:0] weights_layer2_weights_V_q0;
reg   [10:0] weights_layer2_weights_V_address1;
reg    weights_layer2_weights_V_ce1;
wire  signed [10:0] weights_layer2_weights_V_q1;
reg   [6:0] k_reg_269;
reg   [31:0] sum_V_30_reg_280;
reg   [6:0] k_7_reg_293;
reg   [31:0] sum_V_31_reg_304;
reg   [6:0] k_8_reg_317;
reg   [31:0] sum_V_32_reg_328;
reg   [6:0] k_9_reg_341;
reg   [31:0] sum_V_33_reg_352;
wire   [0:0] tmp_fu_365_p3;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln40_fu_373_p1;
reg   [63:0] zext_ln40_reg_965;
wire   [10:0] zext_ln40_1_fu_377_p1;
reg   [10:0] zext_ln40_1_reg_970;
wire   [4:0] trunc_ln40_fu_381_p1;
reg   [4:0] trunc_ln40_reg_975;
wire   [0:0] tmp_19_fu_385_p3;
reg   [0:0] tmp_19_reg_982;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_19_reg_982_pp0_iter1_reg;
wire   [6:0] add_ln44_fu_393_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [5:0] empty_43_fu_427_p1;
reg   [5:0] empty_43_reg_996;
wire   [39:0] mul_ln1192_fu_439_p2;
reg   [39:0] mul_ln1192_reg_1006;
reg    ap_enable_reg_pp0_iter2;
wire   [4:0] or_ln40_fu_534_p2;
reg   [4:0] or_ln40_reg_1026;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln44_fu_539_p1;
reg   [63:0] zext_ln44_reg_1032;
wire   [0:0] tmp_20_fu_543_p3;
reg   [0:0] tmp_20_reg_1037;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state7_pp1_stage0_iter0;
wire    ap_block_state8_pp1_stage0_iter1;
wire    ap_block_state9_pp1_stage0_iter2;
wire    ap_block_pp1_stage0_11001;
reg   [0:0] tmp_20_reg_1037_pp1_iter1_reg;
wire   [6:0] add_ln44_1_fu_551_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [5:0] empty_45_fu_574_p1;
reg   [5:0] empty_45_reg_1051;
wire   [39:0] mul_ln1192_16_fu_586_p2;
reg   [39:0] mul_ln1192_16_reg_1061;
reg    ap_enable_reg_pp1_iter2;
wire   [4:0] or_ln40_1_fu_675_p2;
reg   [4:0] or_ln40_1_reg_1081;
wire    ap_CS_fsm_state10;
wire   [63:0] zext_ln44_1_fu_680_p1;
reg   [63:0] zext_ln44_1_reg_1087;
wire   [0:0] tmp_21_fu_684_p3;
reg   [0:0] tmp_21_reg_1092;
wire    ap_CS_fsm_pp2_stage0;
wire    ap_block_state11_pp2_stage0_iter0;
wire    ap_block_state12_pp2_stage0_iter1;
wire    ap_block_state13_pp2_stage0_iter2;
wire    ap_block_pp2_stage0_11001;
reg   [0:0] tmp_21_reg_1092_pp2_iter1_reg;
wire   [6:0] add_ln44_2_fu_692_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [5:0] or_ln44_2_fu_719_p2;
reg   [5:0] or_ln44_2_reg_1111;
wire   [39:0] mul_ln1192_18_fu_733_p2;
reg   [39:0] mul_ln1192_18_reg_1117;
reg    ap_enable_reg_pp2_iter2;
wire   [4:0] or_ln40_2_fu_815_p2;
reg   [4:0] or_ln40_2_reg_1137;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln44_2_fu_820_p1;
reg   [63:0] zext_ln44_2_reg_1143;
wire   [0:0] tmp_22_fu_824_p3;
reg   [0:0] tmp_22_reg_1148;
wire    ap_CS_fsm_pp3_stage0;
wire    ap_block_state15_pp3_stage0_iter0;
wire    ap_block_state16_pp3_stage0_iter1;
wire    ap_block_state17_pp3_stage0_iter2;
wire    ap_block_pp3_stage0_11001;
reg   [0:0] tmp_22_reg_1148_pp3_iter1_reg;
wire   [6:0] add_ln44_3_fu_832_p2;
reg    ap_enable_reg_pp3_iter0;
wire   [5:0] or_ln44_3_fu_859_p2;
reg   [5:0] or_ln44_3_reg_1167;
wire   [39:0] mul_ln1192_20_fu_873_p2;
reg   [39:0] mul_ln1192_20_reg_1173;
reg    ap_enable_reg_pp3_iter2;
wire   [5:0] add_ln40_fu_955_p2;
wire    ap_CS_fsm_state18;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state7;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state11;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_flush_enable;
reg    ap_enable_reg_pp3_iter1;
reg    ap_condition_pp3_exit_iter1_state16;
reg   [5:0] j_reg_257;
wire    ap_block_pp3_stage0;
wire   [63:0] zext_ln1118_fu_422_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] k_cast7_fu_399_p1;
wire   [63:0] zext_ln1118_30_fu_468_p1;
wire   [63:0] zext_ln42_fu_450_p1;
wire   [63:0] zext_ln1118_24_fu_569_p1;
wire    ap_block_pp1_stage0;
wire   [63:0] k_7_cast8_fu_557_p1;
wire   [63:0] zext_ln1118_25_fu_609_p1;
wire   [63:0] zext_ln42_1_fu_597_p1;
wire   [63:0] zext_ln1118_26_fu_710_p1;
wire    ap_block_pp2_stage0;
wire   [63:0] k_8_cast9_fu_698_p1;
wire   [63:0] zext_ln1118_27_fu_749_p1;
wire   [63:0] zext_ln42_2_fu_739_p1;
wire   [63:0] zext_ln1118_28_fu_850_p1;
wire   [63:0] k_9_cast10_fu_838_p1;
wire   [63:0] zext_ln1118_29_fu_889_p1;
wire   [63:0] zext_ln42_3_fu_879_p1;
wire   [5:0] tmp_s_fu_404_p4;
wire   [11:0] tmp_31_fu_414_p3;
wire   [5:0] or_ln44_fu_445_p2;
wire   [10:0] tmp_32_fu_455_p3;
wire   [10:0] add_ln1118_fu_463_p2;
wire   [39:0] lhs_23_fu_473_p3;
wire   [39:0] ret_V_fu_481_p2;
wire   [31:0] tmp_33_fu_500_p4;
wire   [39:0] lhs_24_fu_510_p3;
wire   [39:0] mul_ln1192_15_fu_494_p2;
wire   [39:0] ret_V_18_fu_518_p2;
wire   [11:0] tmp_34_fu_562_p3;
wire   [5:0] or_ln44_1_fu_592_p2;
wire   [10:0] tmp_35_fu_602_p3;
wire   [39:0] lhs_26_fu_614_p3;
wire   [39:0] ret_V_19_fu_622_p2;
wire   [31:0] tmp_36_fu_641_p4;
wire   [39:0] lhs_27_fu_651_p3;
wire   [39:0] mul_ln1192_17_fu_635_p2;
wire   [39:0] ret_V_20_fu_659_p2;
wire   [11:0] tmp_37_fu_703_p3;
wire   [5:0] empty_47_fu_715_p1;
wire   [10:0] tmp_38_fu_743_p3;
wire   [39:0] lhs_29_fu_754_p3;
wire   [39:0] ret_V_21_fu_762_p2;
wire   [31:0] tmp_39_fu_781_p4;
wire   [39:0] lhs_30_fu_791_p3;
wire   [39:0] mul_ln1192_19_fu_775_p2;
wire   [39:0] ret_V_22_fu_799_p2;
wire   [11:0] tmp_40_fu_843_p3;
wire   [5:0] empty_49_fu_855_p1;
wire   [10:0] tmp_41_fu_883_p3;
wire   [39:0] lhs_32_fu_894_p3;
wire   [39:0] ret_V_23_fu_902_p2;
wire   [31:0] tmp_42_fu_921_p4;
wire   [39:0] lhs_33_fu_931_p3;
wire   [39:0] mul_ln1192_21_fu_915_p2;
wire   [39:0] ret_V_24_fu_939_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
end

nn_inference_hwmm_layer2_weights_layer2_weights_V #(
    .DataWidth( 11 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
weights_layer2_weights_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights_layer2_weights_V_address0),
    .ce0(weights_layer2_weights_V_ce0),
    .q0(weights_layer2_weights_V_q0),
    .address1(weights_layer2_weights_V_address1),
    .ce1(weights_layer2_weights_V_ce1),
    .q1(weights_layer2_weights_V_q1)
);

nn_inference_mul_11s_32s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_11s_32s_40_1_1_U16(
    .din0(weights_layer2_weights_V_q1),
    .din1(input_0_q1),
    .dout(mul_ln1192_fu_439_p2)
);

nn_inference_mul_11s_32s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_11s_32s_40_1_1_U17(
    .din0(weights_layer2_weights_V_q0),
    .din1(input_0_q0),
    .dout(mul_ln1192_15_fu_494_p2)
);

nn_inference_mul_11s_32s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_11s_32s_40_1_1_U18(
    .din0(weights_layer2_weights_V_q1),
    .din1(input_0_q1),
    .dout(mul_ln1192_16_fu_586_p2)
);

nn_inference_mul_11s_32s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_11s_32s_40_1_1_U19(
    .din0(weights_layer2_weights_V_q0),
    .din1(input_0_q0),
    .dout(mul_ln1192_17_fu_635_p2)
);

nn_inference_mul_11s_32s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_11s_32s_40_1_1_U20(
    .din0(weights_layer2_weights_V_q1),
    .din1(input_0_q1),
    .dout(mul_ln1192_18_fu_733_p2)
);

nn_inference_mul_11s_32s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_11s_32s_40_1_1_U21(
    .din0(weights_layer2_weights_V_q0),
    .din1(input_0_q0),
    .dout(mul_ln1192_19_fu_775_p2)
);

nn_inference_mul_11s_32s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_11s_32s_40_1_1_U22(
    .din0(weights_layer2_weights_V_q1),
    .din1(input_0_q1),
    .dout(mul_ln1192_20_fu_873_p2)
);

nn_inference_mul_11s_32s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_11s_32s_40_1_1_U23(
    .din0(weights_layer2_weights_V_q0),
    .din1(input_0_q0),
    .dout(mul_ln1192_21_fu_915_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((tmp_fu_365_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((tmp_fu_365_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp1_exit_iter0_state7) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state7)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state7);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp1_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp2_exit_iter0_state11) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp2_exit_iter0_state11)) begin
                ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state11);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_enable_reg_pp2_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp3_flush_enable)) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state14)) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
        end else if (((1'b1 == ap_CS_fsm_state14) | ((ap_enable_reg_pp3_iter0 == 1'b0) & (1'b1 == ap_condition_pp3_exit_iter1_state16) & (1'b0 == ap_block_pp3_stage0_subdone)))) begin
            ap_enable_reg_pp3_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp3_exit_iter1_state16) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter0;
        end else if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end else if ((1'b1 == ap_CS_fsm_state14)) begin
            ap_enable_reg_pp3_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_reg_257 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        j_reg_257 <= add_ln40_fu_955_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        k_7_reg_293 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (tmp_20_fu_543_p3 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        k_7_reg_293 <= add_ln44_1_fu_551_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        k_8_reg_317 <= 7'd0;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (tmp_21_fu_684_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        k_8_reg_317 <= add_ln44_2_fu_692_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        k_9_reg_341 <= 7'd0;
    end else if (((ap_enable_reg_pp3_iter0 == 1'b1) & (tmp_22_fu_824_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        k_9_reg_341 <= add_ln44_3_fu_832_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_365_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        k_reg_269 <= 7'd0;
    end else if (((tmp_19_fu_385_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_reg_269 <= add_ln44_fu_393_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_365_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        sum_V_30_reg_280 <= 32'd0;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_19_reg_982_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_V_30_reg_280 <= {{ret_V_18_fu_518_p2[39:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sum_V_31_reg_304 <= 32'd0;
    end else if (((ap_enable_reg_pp1_iter2 == 1'b1) & (tmp_20_reg_1037_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        sum_V_31_reg_304 <= {{ret_V_20_fu_659_p2[39:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        sum_V_32_reg_328 <= 32'd0;
    end else if (((ap_enable_reg_pp2_iter2 == 1'b1) & (tmp_21_reg_1092_pp2_iter1_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        sum_V_32_reg_328 <= {{ret_V_22_fu_799_p2[39:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sum_V_33_reg_352 <= 32'd0;
    end else if (((ap_enable_reg_pp3_iter2 == 1'b1) & (tmp_22_reg_1148_pp3_iter1_reg == 1'd0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        sum_V_33_reg_352 <= {{ret_V_24_fu_939_p2[39:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_19_fu_385_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_43_reg_996 <= empty_43_fu_427_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (tmp_20_fu_543_p3 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        empty_45_reg_1051 <= empty_45_fu_574_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (tmp_20_reg_1037 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        mul_ln1192_16_reg_1061 <= mul_ln1192_16_fu_586_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_21_reg_1092 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        mul_ln1192_18_reg_1117 <= mul_ln1192_18_fu_733_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_22_reg_1148 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        mul_ln1192_20_reg_1173 <= mul_ln1192_20_fu_873_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_19_reg_982 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln1192_reg_1006 <= mul_ln1192_fu_439_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        or_ln40_1_reg_1081[0] <= or_ln40_1_fu_675_p2[0];
or_ln40_1_reg_1081[4 : 2] <= or_ln40_1_fu_675_p2[4 : 2];
        zext_ln44_1_reg_1087[0] <= zext_ln44_1_fu_680_p1[0];
zext_ln44_1_reg_1087[4 : 2] <= zext_ln44_1_fu_680_p1[4 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        or_ln40_2_reg_1137[4 : 2] <= or_ln40_2_fu_815_p2[4 : 2];
        zext_ln44_2_reg_1143[4 : 2] <= zext_ln44_2_fu_820_p1[4 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        or_ln40_reg_1026[4 : 1] <= or_ln40_fu_534_p2[4 : 1];
        zext_ln44_reg_1032[4 : 1] <= zext_ln44_fu_539_p1[4 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_21_fu_684_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        or_ln44_2_reg_1111[5 : 1] <= or_ln44_2_fu_719_p2[5 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_22_fu_824_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        or_ln44_3_reg_1167[5 : 1] <= or_ln44_3_fu_859_p2[5 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_19_reg_982 <= k_reg_269[32'd6];
        tmp_19_reg_982_pp0_iter1_reg <= tmp_19_reg_982;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_20_reg_1037 <= k_7_reg_293[32'd6];
        tmp_20_reg_1037_pp1_iter1_reg <= tmp_20_reg_1037;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        tmp_21_reg_1092 <= k_8_reg_317[32'd6];
        tmp_21_reg_1092_pp2_iter1_reg <= tmp_21_reg_1092;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        tmp_22_reg_1148 <= k_9_reg_341[32'd6];
        tmp_22_reg_1148_pp3_iter1_reg <= tmp_22_reg_1148;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_365_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln40_reg_975 <= trunc_ln40_fu_381_p1;
        zext_ln40_1_reg_970[5 : 0] <= zext_ln40_1_fu_377_p1[5 : 0];
        zext_ln40_reg_965[5 : 0] <= zext_ln40_fu_373_p1[5 : 0];
    end
end

always @ (*) begin
    if ((tmp_19_fu_385_p3 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_20_fu_543_p3 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_21_fu_684_p3 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state11 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state11 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_condition_pp3_exit_iter1_state16 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter1_state16 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_22_fu_824_p3 == 1'd1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
        ap_condition_pp3_flush_enable = 1'b1;
    end else begin
        ap_condition_pp3_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_fu_365_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_365_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        input_0_address0 = zext_ln42_3_fu_879_p1;
    end else if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        input_0_address0 = zext_ln42_2_fu_739_p1;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        input_0_address0 = zext_ln42_1_fu_597_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        input_0_address0 = zext_ln42_fu_450_p1;
    end else begin
        input_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        input_0_address1 = k_9_cast10_fu_838_p1;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        input_0_address1 = k_8_cast9_fu_698_p1;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        input_0_address1 = k_7_cast8_fu_557_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        input_0_address1 = k_cast7_fu_399_p1;
    end else begin
        input_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)))) begin
        input_0_ce0 = 1'b1;
    end else begin
        input_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        input_0_ce1 = 1'b1;
    end else begin
        input_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        output_0_address0 = zext_ln44_2_reg_1143;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        output_0_address0 = zext_ln44_1_reg_1087;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        output_0_address0 = zext_ln44_reg_1032;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_0_address0 = zext_ln40_reg_965;
    end else begin
        output_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state6))) begin
        output_0_ce0 = 1'b1;
    end else begin
        output_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        output_0_d0 = sum_V_33_reg_352;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        output_0_d0 = sum_V_32_reg_328;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        output_0_d0 = sum_V_31_reg_304;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_0_d0 = sum_V_30_reg_280;
    end else begin
        output_0_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state6))) begin
        output_0_we0 = 1'b1;
    end else begin
        output_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        weights_layer2_weights_V_address0 = zext_ln1118_29_fu_889_p1;
    end else if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        weights_layer2_weights_V_address0 = zext_ln1118_27_fu_749_p1;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        weights_layer2_weights_V_address0 = zext_ln1118_25_fu_609_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        weights_layer2_weights_V_address0 = zext_ln1118_30_fu_468_p1;
    end else begin
        weights_layer2_weights_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        weights_layer2_weights_V_address1 = zext_ln1118_28_fu_850_p1;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        weights_layer2_weights_V_address1 = zext_ln1118_26_fu_710_p1;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        weights_layer2_weights_V_address1 = zext_ln1118_24_fu_569_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        weights_layer2_weights_V_address1 = zext_ln1118_fu_422_p1;
    end else begin
        weights_layer2_weights_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)))) begin
        weights_layer2_weights_V_ce0 = 1'b1;
    end else begin
        weights_layer2_weights_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        weights_layer2_weights_V_ce1 = 1'b1;
    end else begin
        weights_layer2_weights_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_fu_365_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((tmp_19_fu_385_p3 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((tmp_19_fu_385_p3 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (tmp_20_fu_543_p3 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone)) & ~((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone)) | ((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (tmp_20_fu_543_p3 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (tmp_21_fu_684_p3 == 1'd1) & (1'b0 == ap_block_pp2_stage0_subdone)) & ~((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if ((((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone)) | ((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (tmp_21_fu_684_p3 == 1'd1) & (1'b0 == ap_block_pp2_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_pp3_stage0;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if (~((ap_enable_reg_pp3_iter1 == 1'b1) & (ap_enable_reg_pp3_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((ap_enable_reg_pp3_iter1 == 1'b1) & (ap_enable_reg_pp3_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1118_fu_463_p2 = (tmp_32_fu_455_p3 + zext_ln40_1_reg_970);

assign add_ln40_fu_955_p2 = (j_reg_257 + 6'd4);

assign add_ln44_1_fu_551_p2 = (k_7_reg_293 + 7'd2);

assign add_ln44_2_fu_692_p2 = (k_8_reg_317 + 7'd2);

assign add_ln44_3_fu_832_p2 = (k_9_reg_341 + 7'd2);

assign add_ln44_fu_393_p2 = (k_reg_269 + 7'd2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state11_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp3_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp3_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign empty_43_fu_427_p1 = k_reg_269[5:0];

assign empty_45_fu_574_p1 = k_7_reg_293[5:0];

assign empty_47_fu_715_p1 = k_8_reg_317[5:0];

assign empty_49_fu_855_p1 = k_9_reg_341[5:0];

assign k_7_cast8_fu_557_p1 = k_7_reg_293;

assign k_8_cast9_fu_698_p1 = k_8_reg_317;

assign k_9_cast10_fu_838_p1 = k_9_reg_341;

assign k_cast7_fu_399_p1 = k_reg_269;

assign lhs_23_fu_473_p3 = {{sum_V_30_reg_280}, {8'd0}};

assign lhs_24_fu_510_p3 = {{tmp_33_fu_500_p4}, {8'd0}};

assign lhs_26_fu_614_p3 = {{sum_V_31_reg_304}, {8'd0}};

assign lhs_27_fu_651_p3 = {{tmp_36_fu_641_p4}, {8'd0}};

assign lhs_29_fu_754_p3 = {{sum_V_32_reg_328}, {8'd0}};

assign lhs_30_fu_791_p3 = {{tmp_39_fu_781_p4}, {8'd0}};

assign lhs_32_fu_894_p3 = {{sum_V_33_reg_352}, {8'd0}};

assign lhs_33_fu_931_p3 = {{tmp_42_fu_921_p4}, {8'd0}};

assign or_ln40_1_fu_675_p2 = (trunc_ln40_reg_975 | 5'd2);

assign or_ln40_2_fu_815_p2 = (trunc_ln40_reg_975 | 5'd3);

assign or_ln40_fu_534_p2 = (trunc_ln40_reg_975 | 5'd1);

assign or_ln44_1_fu_592_p2 = (empty_45_reg_1051 | 6'd1);

assign or_ln44_2_fu_719_p2 = (empty_47_fu_715_p1 | 6'd1);

assign or_ln44_3_fu_859_p2 = (empty_49_fu_855_p1 | 6'd1);

assign or_ln44_fu_445_p2 = (empty_43_reg_996 | 6'd1);

assign ret_V_18_fu_518_p2 = (lhs_24_fu_510_p3 + mul_ln1192_15_fu_494_p2);

assign ret_V_19_fu_622_p2 = (lhs_26_fu_614_p3 + mul_ln1192_16_reg_1061);

assign ret_V_20_fu_659_p2 = (lhs_27_fu_651_p3 + mul_ln1192_17_fu_635_p2);

assign ret_V_21_fu_762_p2 = (lhs_29_fu_754_p3 + mul_ln1192_18_reg_1117);

assign ret_V_22_fu_799_p2 = (lhs_30_fu_791_p3 + mul_ln1192_19_fu_775_p2);

assign ret_V_23_fu_902_p2 = (lhs_32_fu_894_p3 + mul_ln1192_20_reg_1173);

assign ret_V_24_fu_939_p2 = (lhs_33_fu_931_p3 + mul_ln1192_21_fu_915_p2);

assign ret_V_fu_481_p2 = (lhs_23_fu_473_p3 + mul_ln1192_reg_1006);

assign tmp_19_fu_385_p3 = k_reg_269[32'd6];

assign tmp_20_fu_543_p3 = k_7_reg_293[32'd6];

assign tmp_21_fu_684_p3 = k_8_reg_317[32'd6];

assign tmp_22_fu_824_p3 = k_9_reg_341[32'd6];

assign tmp_31_fu_414_p3 = {{tmp_s_fu_404_p4}, {j_reg_257}};

assign tmp_32_fu_455_p3 = {{or_ln44_fu_445_p2}, {5'd0}};

assign tmp_33_fu_500_p4 = {{ret_V_fu_481_p2[39:8]}};

assign tmp_34_fu_562_p3 = {{k_7_reg_293}, {or_ln40_reg_1026}};

assign tmp_35_fu_602_p3 = {{or_ln44_1_fu_592_p2}, {or_ln40_reg_1026}};

assign tmp_36_fu_641_p4 = {{ret_V_19_fu_622_p2[39:8]}};

assign tmp_37_fu_703_p3 = {{k_8_reg_317}, {or_ln40_1_reg_1081}};

assign tmp_38_fu_743_p3 = {{or_ln44_2_reg_1111}, {or_ln40_1_reg_1081}};

assign tmp_39_fu_781_p4 = {{ret_V_21_fu_762_p2[39:8]}};

assign tmp_40_fu_843_p3 = {{k_9_reg_341}, {or_ln40_2_reg_1137}};

assign tmp_41_fu_883_p3 = {{or_ln44_3_reg_1167}, {or_ln40_2_reg_1137}};

assign tmp_42_fu_921_p4 = {{ret_V_23_fu_902_p2[39:8]}};

assign tmp_fu_365_p3 = j_reg_257[32'd5];

assign tmp_s_fu_404_p4 = {{k_reg_269[6:1]}};

assign trunc_ln40_fu_381_p1 = j_reg_257[4:0];

assign zext_ln1118_24_fu_569_p1 = tmp_34_fu_562_p3;

assign zext_ln1118_25_fu_609_p1 = tmp_35_fu_602_p3;

assign zext_ln1118_26_fu_710_p1 = tmp_37_fu_703_p3;

assign zext_ln1118_27_fu_749_p1 = tmp_38_fu_743_p3;

assign zext_ln1118_28_fu_850_p1 = tmp_40_fu_843_p3;

assign zext_ln1118_29_fu_889_p1 = tmp_41_fu_883_p3;

assign zext_ln1118_30_fu_468_p1 = add_ln1118_fu_463_p2;

assign zext_ln1118_fu_422_p1 = tmp_31_fu_414_p3;

assign zext_ln40_1_fu_377_p1 = j_reg_257;

assign zext_ln40_fu_373_p1 = j_reg_257;

assign zext_ln42_1_fu_597_p1 = or_ln44_1_fu_592_p2;

assign zext_ln42_2_fu_739_p1 = or_ln44_2_reg_1111;

assign zext_ln42_3_fu_879_p1 = or_ln44_3_reg_1167;

assign zext_ln42_fu_450_p1 = or_ln44_fu_445_p2;

assign zext_ln44_1_fu_680_p1 = or_ln40_1_fu_675_p2;

assign zext_ln44_2_fu_820_p1 = or_ln40_2_fu_815_p2;

assign zext_ln44_fu_539_p1 = or_ln40_fu_534_p2;

always @ (posedge ap_clk) begin
    zext_ln40_reg_965[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln40_1_reg_970[10:6] <= 5'b00000;
    or_ln40_reg_1026[0] <= 1'b1;
    zext_ln44_reg_1032[0] <= 1'b1;
    zext_ln44_reg_1032[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    or_ln40_1_reg_1081[1] <= 1'b1;
    zext_ln44_1_reg_1087[1] <= 1'b1;
    zext_ln44_1_reg_1087[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    or_ln44_2_reg_1111[0] <= 1'b1;
    or_ln40_2_reg_1137[1:0] <= 2'b11;
    zext_ln44_2_reg_1143[1:0] <= 2'b11;
    zext_ln44_2_reg_1143[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    or_ln44_3_reg_1167[0] <= 1'b1;
end

endmodule //nn_inference_hwmm_layer2
